version: "3.4"

x-common-variables:
  &common-variables
  CHAT_COORD_HOST: chat-coordinator
  SRV_HOST: mafia-server
  PLAYERS_CNT: 4
  USE_BOT: use

services:
  rabbitmq:
    image: "rabbitmq:3.11.6-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
  # mafia-server:
  #   image: michicosun/mafia-server
  #   environment: *common-variables
  #   ports:
  #     - 9000:9000/tcp
  # bot-1:
  #   image: michicosun/mafia-bot
  #   environment: *common-variables
  # bot-2:
  #   image: michicosun/mafia-bot
  #   environment: *common-variables
  # bot-3:
  #   image: michicosun/mafia-bot
  #   environment: *common-variables
