version: "3.4"

x-common-variables:
  &common-variables
  RABBIT_HOST: rabbitmq
  REGISTRY_HOST: mafia-registry
  SRV_HOST: mafia-server
  PLAYERS_CNT: 4
  USE_BOT: use

services:
  rabbitmq:
    image: "rabbitmq:3.11.6-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"

  mafia-registry:
    image: michicosun/mafia-registry
    environment: *common-variables
    ports:
      - 8080:8080/tcp
    depends_on:
      - rabbitmq
    restart: on-failure

  mafia-server:
    image: michicosun/mafia-server
    environment: *common-variables
    ports:
      - 9000:9000/tcp
    depends_on:
      - mafia-registry
    restart: on-failure

  bot-1:
    image: michicosun/mafia-bot
    environment: *common-variables
    depends_on:
      - mafia-server

  bot-2:
    image: michicosun/mafia-bot
    environment: *common-variables
    depends_on:
      - mafia-server

  bot-3:
    image: michicosun/mafia-bot
    environment: *common-variables
    depends_on:
      - mafia-server
