// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Player struct {
	Login string `json:"login"`
	Role  string `json:"role"`
	Alive bool   `json:"alive"`
}

type PlayerInfo struct {
	Login string `json:"login"`
	Role  string `json:"role"`
}

type PlayerStatus struct {
	Login string `json:"login"`
	Alive bool   `json:"alive"`
}

type Round struct {
	ID        string    `json:"id"`
	StartedAt int       `json:"started_at"`
	Players   []*Player `json:"players"`
}

type RoundInfo struct {
	ID        string `json:"id"`
	StartedAt int    `json:"started_at"`
}
