// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mafia.proto

package mafia

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionType int32

const (
	ActionType_Init      ActionType = 0
	ActionType_Vote      ActionType = 1
	ActionType_DoNothing ActionType = 2
)

var ActionType_name = map[int32]string{
	0: "Init",
	1: "Vote",
	2: "DoNothing",
}

var ActionType_value = map[string]int32{
	"Init":      0,
	"Vote":      1,
	"DoNothing": 2,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{0}
}

type EventType int32

const (
	EventType_GameStart          EventType = 0
	EventType_VoteRequest        EventType = 1
	EventType_SystemMessage      EventType = 2
	EventType_MafiaCheckResponse EventType = 3
	EventType_Death              EventType = 4
	EventType_GameEnd            EventType = 5
)

var EventType_name = map[int32]string{
	0: "GameStart",
	1: "VoteRequest",
	2: "SystemMessage",
	3: "MafiaCheckResponse",
	4: "Death",
	5: "GameEnd",
}

var EventType_value = map[string]int32{
	"GameStart":          0,
	"VoteRequest":        1,
	"SystemMessage":      2,
	"MafiaCheckResponse": 3,
	"Death":              4,
	"GameEnd":            5,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1}
}

type Role int32

const (
	Role_Civilian Role = 0
	Role_Mafia    Role = 1
	Role_Sheriff  Role = 2
)

var Role_name = map[int32]string{
	0: "Civilian",
	1: "Mafia",
	2: "Sheriff",
}

var Role_value = map[string]int32{
	"Civilian": 0,
	"Mafia":    1,
	"Sheriff":  2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{2}
}

type Action struct {
	// Types that are valid to be assigned to Data:
	//	*Action_Init_
	//	*Action_Vote_
	//	*Action_DoNothing_
	Data                 isAction_Data `protobuf_oneof:"data"`
	Type                 ActionType    `protobuf:"varint,4,opt,name=type,proto3,enum=mafia.ActionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

type isAction_Data interface {
	isAction_Data()
}

type Action_Init_ struct {
	Init *Action_Init `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type Action_Vote_ struct {
	Vote *Action_Vote `protobuf:"bytes,2,opt,name=vote,proto3,oneof"`
}

type Action_DoNothing_ struct {
	DoNothing *Action_DoNothing `protobuf:"bytes,3,opt,name=do_nothing,json=doNothing,proto3,oneof"`
}

func (*Action_Init_) isAction_Data() {}

func (*Action_Vote_) isAction_Data() {}

func (*Action_DoNothing_) isAction_Data() {}

func (m *Action) GetData() isAction_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Action) GetInit() *Action_Init {
	if x, ok := m.GetData().(*Action_Init_); ok {
		return x.Init
	}
	return nil
}

func (m *Action) GetVote() *Action_Vote {
	if x, ok := m.GetData().(*Action_Vote_); ok {
		return x.Vote
	}
	return nil
}

func (m *Action) GetDoNothing() *Action_DoNothing {
	if x, ok := m.GetData().(*Action_DoNothing_); ok {
		return x.DoNothing
	}
	return nil
}

func (m *Action) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return ActionType_Init
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Action) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Action_Init_)(nil),
		(*Action_Vote_)(nil),
		(*Action_DoNothing_)(nil),
	}
}

type Action_Init struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action_Init) Reset()         { *m = Action_Init{} }
func (m *Action_Init) String() string { return proto.CompactTextString(m) }
func (*Action_Init) ProtoMessage()    {}
func (*Action_Init) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{0, 0}
}

func (m *Action_Init) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action_Init.Unmarshal(m, b)
}
func (m *Action_Init) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action_Init.Marshal(b, m, deterministic)
}
func (m *Action_Init) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action_Init.Merge(m, src)
}
func (m *Action_Init) XXX_Size() int {
	return xxx_messageInfo_Action_Init.Size(m)
}
func (m *Action_Init) XXX_DiscardUnknown() {
	xxx_messageInfo_Action_Init.DiscardUnknown(m)
}

var xxx_messageInfo_Action_Init proto.InternalMessageInfo

func (m *Action_Init) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Action_Vote struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action_Vote) Reset()         { *m = Action_Vote{} }
func (m *Action_Vote) String() string { return proto.CompactTextString(m) }
func (*Action_Vote) ProtoMessage()    {}
func (*Action_Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{0, 1}
}

func (m *Action_Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action_Vote.Unmarshal(m, b)
}
func (m *Action_Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action_Vote.Marshal(b, m, deterministic)
}
func (m *Action_Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action_Vote.Merge(m, src)
}
func (m *Action_Vote) XXX_Size() int {
	return xxx_messageInfo_Action_Vote.Size(m)
}
func (m *Action_Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Action_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Action_Vote proto.InternalMessageInfo

func (m *Action_Vote) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Action_Vote) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Action_DoNothing struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action_DoNothing) Reset()         { *m = Action_DoNothing{} }
func (m *Action_DoNothing) String() string { return proto.CompactTextString(m) }
func (*Action_DoNothing) ProtoMessage()    {}
func (*Action_DoNothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{0, 2}
}

func (m *Action_DoNothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action_DoNothing.Unmarshal(m, b)
}
func (m *Action_DoNothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action_DoNothing.Marshal(b, m, deterministic)
}
func (m *Action_DoNothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action_DoNothing.Merge(m, src)
}
func (m *Action_DoNothing) XXX_Size() int {
	return xxx_messageInfo_Action_DoNothing.Size(m)
}
func (m *Action_DoNothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Action_DoNothing.DiscardUnknown(m)
}

var xxx_messageInfo_Action_DoNothing proto.InternalMessageInfo

func (m *Action_DoNothing) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type Event struct {
	// Types that are valid to be assigned to Data:
	//	*Event_GameStart_
	//	*Event_VoteRequest_
	//	*Event_Message
	//	*Event_MafiaCheckResponse_
	//	*Event_Death_
	//	*Event_GameEnd_
	Data                 isEvent_Data `protobuf_oneof:"data"`
	Type                 EventType    `protobuf:"varint,7,opt,name=type,proto3,enum=mafia.EventType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Data interface {
	isEvent_Data()
}

type Event_GameStart_ struct {
	GameStart *Event_GameStart `protobuf:"bytes,1,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type Event_VoteRequest_ struct {
	VoteRequest *Event_VoteRequest `protobuf:"bytes,2,opt,name=vote_request,json=voteRequest,proto3,oneof"`
}

type Event_Message struct {
	Message *Event_SystemMessage `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type Event_MafiaCheckResponse_ struct {
	MafiaCheckResponse *Event_MafiaCheckResponse `protobuf:"bytes,4,opt,name=mafia_check_response,json=mafiaCheckResponse,proto3,oneof"`
}

type Event_Death_ struct {
	Death *Event_Death `protobuf:"bytes,5,opt,name=death,proto3,oneof"`
}

type Event_GameEnd_ struct {
	GameEnd *Event_GameEnd `protobuf:"bytes,6,opt,name=game_end,json=gameEnd,proto3,oneof"`
}

func (*Event_GameStart_) isEvent_Data() {}

func (*Event_VoteRequest_) isEvent_Data() {}

func (*Event_Message) isEvent_Data() {}

func (*Event_MafiaCheckResponse_) isEvent_Data() {}

func (*Event_Death_) isEvent_Data() {}

func (*Event_GameEnd_) isEvent_Data() {}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetGameStart() *Event_GameStart {
	if x, ok := m.GetData().(*Event_GameStart_); ok {
		return x.GameStart
	}
	return nil
}

func (m *Event) GetVoteRequest() *Event_VoteRequest {
	if x, ok := m.GetData().(*Event_VoteRequest_); ok {
		return x.VoteRequest
	}
	return nil
}

func (m *Event) GetMessage() *Event_SystemMessage {
	if x, ok := m.GetData().(*Event_Message); ok {
		return x.Message
	}
	return nil
}

func (m *Event) GetMafiaCheckResponse() *Event_MafiaCheckResponse {
	if x, ok := m.GetData().(*Event_MafiaCheckResponse_); ok {
		return x.MafiaCheckResponse
	}
	return nil
}

func (m *Event) GetDeath() *Event_Death {
	if x, ok := m.GetData().(*Event_Death_); ok {
		return x.Death
	}
	return nil
}

func (m *Event) GetGameEnd() *Event_GameEnd {
	if x, ok := m.GetData().(*Event_GameEnd_); ok {
		return x.GameEnd
	}
	return nil
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_GameStart
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_GameStart_)(nil),
		(*Event_VoteRequest_)(nil),
		(*Event_Message)(nil),
		(*Event_MafiaCheckResponse_)(nil),
		(*Event_Death_)(nil),
		(*Event_GameEnd_)(nil),
	}
}

type Event_GameStart struct {
	Role                 Role     `protobuf:"varint,1,opt,name=role,proto3,enum=mafia.Role" json:"role,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Group                []string `protobuf:"bytes,3,rep,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_GameStart) Reset()         { *m = Event_GameStart{} }
func (m *Event_GameStart) String() string { return proto.CompactTextString(m) }
func (*Event_GameStart) ProtoMessage()    {}
func (*Event_GameStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1, 0}
}

func (m *Event_GameStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_GameStart.Unmarshal(m, b)
}
func (m *Event_GameStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_GameStart.Marshal(b, m, deterministic)
}
func (m *Event_GameStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_GameStart.Merge(m, src)
}
func (m *Event_GameStart) XXX_Size() int {
	return xxx_messageInfo_Event_GameStart.Size(m)
}
func (m *Event_GameStart) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_GameStart.DiscardUnknown(m)
}

var xxx_messageInfo_Event_GameStart proto.InternalMessageInfo

func (m *Event_GameStart) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_Civilian
}

func (m *Event_GameStart) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Event_GameStart) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

type Event_VoteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_VoteRequest) Reset()         { *m = Event_VoteRequest{} }
func (m *Event_VoteRequest) String() string { return proto.CompactTextString(m) }
func (*Event_VoteRequest) ProtoMessage()    {}
func (*Event_VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1, 1}
}

func (m *Event_VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_VoteRequest.Unmarshal(m, b)
}
func (m *Event_VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_VoteRequest.Marshal(b, m, deterministic)
}
func (m *Event_VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_VoteRequest.Merge(m, src)
}
func (m *Event_VoteRequest) XXX_Size() int {
	return xxx_messageInfo_Event_VoteRequest.Size(m)
}
func (m *Event_VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Event_VoteRequest proto.InternalMessageInfo

type Event_SystemMessage struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_SystemMessage) Reset()         { *m = Event_SystemMessage{} }
func (m *Event_SystemMessage) String() string { return proto.CompactTextString(m) }
func (*Event_SystemMessage) ProtoMessage()    {}
func (*Event_SystemMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1, 2}
}

func (m *Event_SystemMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_SystemMessage.Unmarshal(m, b)
}
func (m *Event_SystemMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_SystemMessage.Marshal(b, m, deterministic)
}
func (m *Event_SystemMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_SystemMessage.Merge(m, src)
}
func (m *Event_SystemMessage) XXX_Size() int {
	return xxx_messageInfo_Event_SystemMessage.Size(m)
}
func (m *Event_SystemMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_SystemMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Event_SystemMessage proto.InternalMessageInfo

func (m *Event_SystemMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Event_MafiaCheckResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsMafia              bool     `protobuf:"varint,2,opt,name=is_mafia,json=isMafia,proto3" json:"is_mafia,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_MafiaCheckResponse) Reset()         { *m = Event_MafiaCheckResponse{} }
func (m *Event_MafiaCheckResponse) String() string { return proto.CompactTextString(m) }
func (*Event_MafiaCheckResponse) ProtoMessage()    {}
func (*Event_MafiaCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1, 3}
}

func (m *Event_MafiaCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_MafiaCheckResponse.Unmarshal(m, b)
}
func (m *Event_MafiaCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_MafiaCheckResponse.Marshal(b, m, deterministic)
}
func (m *Event_MafiaCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_MafiaCheckResponse.Merge(m, src)
}
func (m *Event_MafiaCheckResponse) XXX_Size() int {
	return xxx_messageInfo_Event_MafiaCheckResponse.Size(m)
}
func (m *Event_MafiaCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_MafiaCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Event_MafiaCheckResponse proto.InternalMessageInfo

func (m *Event_MafiaCheckResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event_MafiaCheckResponse) GetIsMafia() bool {
	if m != nil {
		return m.IsMafia
	}
	return false
}

type Event_Death struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Death) Reset()         { *m = Event_Death{} }
func (m *Event_Death) String() string { return proto.CompactTextString(m) }
func (*Event_Death) ProtoMessage()    {}
func (*Event_Death) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1, 4}
}

func (m *Event_Death) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Death.Unmarshal(m, b)
}
func (m *Event_Death) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Death.Marshal(b, m, deterministic)
}
func (m *Event_Death) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Death.Merge(m, src)
}
func (m *Event_Death) XXX_Size() int {
	return xxx_messageInfo_Event_Death.Size(m)
}
func (m *Event_Death) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Death.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Death proto.InternalMessageInfo

func (m *Event_Death) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Event_GameEnd struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_GameEnd) Reset()         { *m = Event_GameEnd{} }
func (m *Event_GameEnd) String() string { return proto.CompactTextString(m) }
func (*Event_GameEnd) ProtoMessage()    {}
func (*Event_GameEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7077fdb094f3bc8b, []int{1, 5}
}

func (m *Event_GameEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_GameEnd.Unmarshal(m, b)
}
func (m *Event_GameEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_GameEnd.Marshal(b, m, deterministic)
}
func (m *Event_GameEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_GameEnd.Merge(m, src)
}
func (m *Event_GameEnd) XXX_Size() int {
	return xxx_messageInfo_Event_GameEnd.Size(m)
}
func (m *Event_GameEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_GameEnd.DiscardUnknown(m)
}

var xxx_messageInfo_Event_GameEnd proto.InternalMessageInfo

func (m *Event_GameEnd) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterEnum("mafia.ActionType", ActionType_name, ActionType_value)
	proto.RegisterEnum("mafia.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("mafia.Role", Role_name, Role_value)
	proto.RegisterType((*Action)(nil), "mafia.Action")
	proto.RegisterType((*Action_Init)(nil), "mafia.Action.Init")
	proto.RegisterType((*Action_Vote)(nil), "mafia.Action.Vote")
	proto.RegisterType((*Action_DoNothing)(nil), "mafia.Action.DoNothing")
	proto.RegisterType((*Event)(nil), "mafia.Event")
	proto.RegisterType((*Event_GameStart)(nil), "mafia.Event.GameStart")
	proto.RegisterType((*Event_VoteRequest)(nil), "mafia.Event.VoteRequest")
	proto.RegisterType((*Event_SystemMessage)(nil), "mafia.Event.SystemMessage")
	proto.RegisterType((*Event_MafiaCheckResponse)(nil), "mafia.Event.MafiaCheckResponse")
	proto.RegisterType((*Event_Death)(nil), "mafia.Event.Death")
	proto.RegisterType((*Event_GameEnd)(nil), "mafia.Event.GameEnd")
}

func init() { proto.RegisterFile("mafia.proto", fileDescriptor_7077fdb094f3bc8b) }

var fileDescriptor_7077fdb094f3bc8b = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0x93, 0x36, 0x69, 0x9b, 0x93, 0x76, 0xf3, 0x8e, 0xa6, 0xbd, 0x79, 0x83, 0xd0, 0xa6,
	0x01, 0x52, 0x55, 0x41, 0x07, 0x45, 0x02, 0x24, 0xb4, 0x0b, 0xf6, 0x07, 0xca, 0xc5, 0xb8, 0x70,
	0x11, 0x17, 0x08, 0xa9, 0x0a, 0x8d, 0xdb, 0x5a, 0x34, 0x76, 0x49, 0xbc, 0x8a, 0x7e, 0x27, 0xae,
	0xf8, 0x84, 0xc8, 0x4e, 0xd2, 0x35, 0xac, 0x37, 0x91, 0x8f, 0xcf, 0xef, 0x58, 0x8f, 0x9f, 0x3c,
	0x09, 0xf8, 0x49, 0x34, 0xe5, 0x51, 0x7f, 0x99, 0x4a, 0x25, 0xd1, 0x35, 0xc5, 0xe9, 0x9f, 0x1a,
	0x34, 0xde, 0x4d, 0x14, 0x97, 0x02, 0xbb, 0xe0, 0x70, 0xc1, 0x55, 0x60, 0x9f, 0xd8, 0x5d, 0x7f,
	0x80, 0xfd, 0x9c, 0xce, 0x9b, 0xfd, 0x8f, 0x82, 0xab, 0xa1, 0x45, 0x0d, 0xa1, 0xc9, 0x95, 0x54,
	0x2c, 0xa8, 0xed, 0x22, 0xbf, 0x48, 0xc5, 0x34, 0xa9, 0x09, 0x7c, 0x03, 0x10, 0xcb, 0xb1, 0x90,
	0x6a, 0xce, 0xc5, 0x2c, 0xa8, 0x1b, 0xfe, 0xbf, 0x2a, 0x7f, 0x25, 0x3f, 0xe5, 0xed, 0xa1, 0x45,
	0xbd, 0xb8, 0x2c, 0xf0, 0x09, 0x38, 0x6a, 0xbd, 0x64, 0x81, 0x73, 0x62, 0x77, 0xf7, 0x06, 0x07,
	0x95, 0x99, 0xcf, 0xeb, 0x25, 0xa3, 0xa6, 0x1d, 0x86, 0xe0, 0x68, 0x69, 0x88, 0xe0, 0x88, 0x28,
	0x61, 0x46, 0xbc, 0x47, 0xcd, 0x3a, 0xec, 0x83, 0xa3, 0xc5, 0xe8, 0xde, 0x34, 0x95, 0x49, 0xd9,
	0xd3, 0xeb, 0x0d, 0x5f, 0xdb, 0xe2, 0x8f, 0xc1, 0xdb, 0x88, 0xd9, 0x35, 0x74, 0xd1, 0x00, 0x27,
	0x8e, 0x54, 0x74, 0xfa, 0xdb, 0x05, 0xf7, 0x7a, 0xc5, 0x84, 0xc2, 0xd7, 0x00, 0xb3, 0x28, 0x61,
	0xe3, 0x4c, 0x45, 0x69, 0xe9, 0xdc, 0x51, 0xa1, 0xd5, 0x10, 0xfd, 0x0f, 0x51, 0xc2, 0x46, 0xba,
	0xab, 0xaf, 0x37, 0x2b, 0x0b, 0x3c, 0x87, 0xb6, 0x36, 0x68, 0x9c, 0xb2, 0x9f, 0xb7, 0x2c, 0x53,
	0x85, 0x95, 0x41, 0x65, 0x54, 0x8b, 0xa7, 0x79, 0x7f, 0x68, 0x51, 0x7f, 0x75, 0x57, 0xe2, 0x2b,
	0x68, 0x26, 0x2c, 0xcb, 0xa2, 0x19, 0x2b, 0x4c, 0x0d, 0x2b, 0x93, 0xa3, 0x75, 0xa6, 0x58, 0x72,
	0x93, 0x13, 0x43, 0x8b, 0x96, 0x30, 0x8e, 0xe0, 0xd0, 0x70, 0xe3, 0xc9, 0x9c, 0x4d, 0x7e, 0x8c,
	0x53, 0x96, 0x2d, 0xa5, 0xc8, 0x72, 0x97, 0xfd, 0xc1, 0x71, 0xe5, 0x90, 0x1b, 0xbd, 0xbe, 0xd4,
	0x1c, 0x2d, 0xb0, 0xa1, 0x45, 0x31, 0xb9, 0xb7, 0x8b, 0x3d, 0x70, 0x63, 0x16, 0xa9, 0x79, 0xe0,
	0x56, 0xf2, 0x90, 0x9f, 0x72, 0xa5, 0x3b, 0x43, 0x8b, 0xe6, 0x08, 0xbe, 0x80, 0x96, 0x31, 0x8c,
	0x89, 0x38, 0x68, 0x18, 0xfc, 0xf0, 0x9e, 0x5d, 0xd7, 0x22, 0xd6, 0x9a, 0x67, 0xf9, 0x12, 0x1f,
	0x17, 0x49, 0x68, 0x9a, 0x24, 0x90, 0x6d, 0x7c, 0x2b, 0x08, 0xdf, 0xc0, 0xdb, 0x58, 0x8d, 0xc7,
	0xe0, 0xa4, 0x72, 0x91, 0xa7, 0x61, 0x6f, 0xe0, 0x17, 0x23, 0x54, 0x2e, 0x18, 0x35, 0x0d, 0x0c,
	0xa0, 0xb9, 0x5c, 0x44, 0x6b, 0x96, 0x66, 0x41, 0xed, 0xa4, 0xde, 0xf5, 0x68, 0x59, 0xe2, 0x21,
	0xb8, 0xb3, 0x54, 0xde, 0x2e, 0x83, 0xba, 0xd9, 0xcf, 0x8b, 0xb0, 0x03, 0xfe, 0xd6, 0xdb, 0x08,
	0x1f, 0x41, 0xa7, 0x62, 0xb1, 0x4e, 0x8b, 0x62, 0xbf, 0x54, 0x99, 0x16, 0xbd, 0x0e, 0x2f, 0x01,
	0xef, 0x5b, 0xb8, 0x2b, 0xa8, 0xf8, 0x3f, 0xb4, 0x78, 0x36, 0x36, 0x22, 0x4d, 0x10, 0x5a, 0xb4,
	0xc9, 0x33, 0x33, 0x1b, 0x3e, 0x00, 0xd7, 0x38, 0xb8, 0x33, 0xe0, 0x0f, 0xa1, 0x59, 0xf8, 0xb5,
	0x4b, 0x40, 0x19, 0xd7, 0xde, 0x19, 0xc0, 0xdd, 0x77, 0x83, 0xad, 0xfc, 0x8b, 0x21, 0x96, 0x5e,
	0xe9, 0x4b, 0x11, 0x1b, 0x3b, 0x5b, 0xc9, 0x27, 0xb5, 0x9e, 0x00, 0x6f, 0x63, 0xaf, 0xee, 0x6d,
	0x8c, 0x25, 0x16, 0xee, 0x57, 0x9c, 0x20, 0x36, 0x1e, 0xfc, 0xe3, 0x05, 0xa9, 0xe1, 0xd1, 0xae,
	0x9b, 0x93, 0x3a, 0x7a, 0xc5, 0x65, 0x88, 0x83, 0xfe, 0x46, 0x3a, 0x71, 0x7b, 0x4f, 0xc1, 0xd1,
	0xef, 0x06, 0xdb, 0xd0, 0xba, 0xe4, 0x2b, 0xbe, 0xe0, 0x91, 0x20, 0x96, 0xa6, 0xcd, 0x29, 0xc4,
	0xd6, 0xf4, 0x68, 0xce, 0x52, 0x3e, 0x9d, 0x92, 0xda, 0xe0, 0x1c, 0xda, 0x66, 0x7f, 0xc4, 0xd2,
	0x15, 0x9f, 0x30, 0x7c, 0x06, 0xad, 0xf7, 0x5c, 0xc4, 0xfa, 0x38, 0xec, 0x54, 0xfe, 0x13, 0x61,
	0x7b, 0x3b, 0x2c, 0xa7, 0x56, 0xd7, 0x7e, 0x6e, 0x5f, 0xec, 0x7f, 0xed, 0xf4, 0xcf, 0xcc, 0xf6,
	0x5b, 0xf3, 0xfc, 0xde, 0x30, 0x3f, 0xc4, 0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x12,
	0xb4, 0xee, 0x1f, 0x05, 0x00, 0x00,
}
